### ISSUE TITLE
Function "masterKeyFromEntropy" actual is "masterKeyFromSeed"

### ISSUE THREAD

**Issue by agentsib** [furqansiddiqui/bip32-keypair-php#1]
Hello!

I think functions masterKeyFromEntropy and masterKeyFromSeed mixed up.

I create account in MetaMask and export secret data. Please, look in my demo project:

https://github.com/agentsib/eth-demo

```php
<?php
$mnemonic = 'ceiling mixed inmate donate arctic scene pave address kangaroo ill crush neck';

$wallet1 = '0x3a1108329e10323449d61fb60fcc531705D24125';
$private1 = 'f429ddc1d39eac60594e0366c7d7763afa78f342196fa4bb48fe9fa134fa5378';

$wallet2 = '0xDfF2A3e87f98304321CA3e4cE7E16dBa2051fbd8';
$private2 = '379169e17fb1b40e188df9489e1c044ee338ed2070ebae83d3d816466128ccff';


$mnemonicObj = \FurqanSiddiqui\BIP39\BIP39::Words($mnemonic);

$bip32 = new \FurqanSiddiqui\BIP32\BIP32(
    new \FurqanSiddiqui\ECDSA\Curves\Secp256k1(),
    \FurqanSiddiqui\Ethereum\Networks\Ethereum::Mainnet()
);

$wrongHdKeyPear = $bip32->masterKeyFromSeed(new \FurqanSiddiqui\BIP32\Buffers\Bits512($mnemonicObj->generateSeed()));

echo 'WRONG:'.PHP_EOL.PHP_EOL;
$wrongPrivate1 = $wrongHdKeyPear->derivePath("m/44'/60'/0'/0/0")->privateKey()->eccPrivateKey->private->toBase16();
echo sprintf('%s != %s', $private1, $wrongPrivate1).PHP_EOL;
$wrongPrivate2 = $wrongHdKeyPear->derivePath("m/44'/60'/0'/0/1")->privateKey()->eccPrivateKey->private->toBase16();
echo sprintf('%s != %s', $private2, $wrongPrivate2).PHP_EOL;


// Whats correct
$rightHdKeyPear = $bip32->masterKeyFromEntropy(new \FurqanSiddiqui\BIP32\Buffers\Bits512($mnemonicObj->generateSeed()));

echo PHP_EOL.PHP_EOL.'CORRECT:'.PHP_EOL.PHP_EOL;
$rightPrivate1 = $rightHdKeyPear->derivePath("m/44'/60'/0'/0/0")->privateKey()->eccPrivateKey->private->toBase16();
echo sprintf('%s == %s', $private1, $rightPrivate1).PHP_EOL;
$rightPrivate2 = $rightHdKeyPear->derivePath("m/44'/60'/0'/0/1")->privateKey()->eccPrivateKey->private->toBase16();
echo sprintf('%s == %s', $private2, $rightPrivate2).PHP_EOL;
```

In project https://github.com/furqansiddiqui/ethereum-php issue exists to.

Thank you for you projects!

**Comment by furqansiddiqui** [comment]
Actually, if you check the source code... Method `masterKeyFromEntropy` also uses the `masterKeyFromSeed` but first it applies `HMAC` using "Bitcoin seed" as key, as per BIP-0032 specification: 

```php
    public function masterKeyFromEntropy(AbstractByteArray $prv): MasterKeyPair
    {
        return $this->masterKeyFromSeed($this->hmacEntropy($prv));
    }
```

`Calculate I = HMAC-SHA512(Key = "Bitcoin seed", Data = S)`
[https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)

so, `masterKeyFromEntropy` is supposed to generate BIP0032 specific seed from the given entropy (not necessarily a Mnemonic seed), while `masterKeyFromSeed` assumes that argument given is 32 bytes entropy and 32 bytes chain code. This is there for "custom" entries to be able to work, like the ones that do not use "Bitcoin seed" as defined in BIP0032 for hashing.

Also, FYI many software implementations also vary therefore just need to find right method if you wish to re-create same private keys as in MetaMask or any other wallet for that matter. Also, Off-topic, while keys in your `$wrongHdKeyPear` do not match with MetaMask, they are all still valid private keys and addresses that you can sign transactions from.

Kindly check `tests` directory where it passes all BIP-0032 test vectors, here is a snippet of test execution:

```php
$m = $bip32->masterKeyFromEntropy(\Comely\Buffer\Buffer::fromBase16($vector["seed"])); // Arbitrary entropy, no pattern
```

Please feel free to reopen if you think there's been any mistake.

**Comment by furqansiddiqui** [comment]
Just to clarify:

```php
public function masterKeyFromSeed(Bits512 $seed): MasterKeyPair
```

`masterKeyFromSeed` expects a complete 64 byte seed (one part private key and one part chain code), that is why the argument expects a fixed 64 byte length and method assumes you are giving a complete seed.

```php
public function masterKeyFromEntropy(AbstractByteArray $prv): MasterKeyPair
```
`masterKeyFromEntropy` on other hand will take any entropy, and HMAC it with `AbstractNetworkConfig::$hmacSeed` configured value which defaults to "Bitcoin seed" but can be changed for custom/different networks.
